<div>
    <h2>ABOUT INDEX PAGE</h2>
    <nav class="nav">
        <div class="btn-group">
        <a href="\home" class="btn btn-secondary">HOME PAGE</a>
        <a href="\home\about" class="btn btn-secondary active">About</a>
        <a href="\home\help" class="btn btn-secondary">Help</a>
        <a href="\home\contacts" class="btn btn-secondary">Contacts</a>
        </div>
    </nav>
</div>