<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Task 24.MVC</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script defer src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</head>
<body>
    <header class="header">
        <h1>Hello, Skillfactory!</h1>    
        <h2>HEADER</h2>
    </header>

    <main class="main">
        <h2 m-auto>MAIN</h2>

        <div class="container-fluid">
            <?php include_once VIEW . $content_view ?>
        </div>
        
        <div class="container-fluid mt-3">
            <div class="row">
                <p>
                    <img src="../images/composer_bash.png" alt="bash">
                </p>
            </div>
            <div class="row">
                <p>
                    <img src="../images/phpinfo_gd.png" alt="info">
                </p>
            </div>        
        </div>
    </main>

    <footer class="footer">
        <h2>FOOTER</h2>
    </footer>

</body>
</html>